"""Add confidence to facts

Revision ID: 68d30ddf6f61
Revises: 
Create Date: 2026-02-09 11:07:14.144321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d30ddf6f61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('diagnose_users')
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True))

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_column('confidence')

    op.create_table('diagnose_users',
    sa.Column('diagnose_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['diagnose_id'], ['diagnoses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###
