"""Remove confidence column from facts

Revision ID: 9bd4b81218e8
Revises: 1c231fdc1ee5
Create Date: 2026-09-01 22:59:01.632248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd4b81218e8'
down_revision = '1c231fdc1ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_column('confidence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.NUMERIC(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###
